name: Deploy to GitHub Pages

on:
  push:
    branches: [ "Presentation" ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Publish .NET Core Project
      working-directory: ./Presentation 
      run: dotnet publish Presentation.csproj -c Release -o release --nologo
    
    # Subsequent steps remain unchanged as paths are relative to the root
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/LinearAlgebra\/" \/>/g' Presentation/release/wwwroot/index.html  
    
    - name: Update PWA manifest paths
      run: | 
        sed -i 's/"start_url": "\.\/"/"start_url": "\/LinearAlgebra\/"/g' Presentation/release/wwwroot/manifest.webmanifest
        sed -i 's/"id": "\.\/"/"id": "\/LinearAlgebra\/"/g' Presentation/release/wwwroot/manifest.webmanifest

    - name: Update integrity hash
      run: |
        # Calculate new SHA-256 hash for index.html
        NEW_HASH=$(openssl dgst -sha256 -binary Presentation/release/wwwroot/index.html | openssl base64 -A)
    
        # Update integrity hash in index.html
        sed -i "s|integrity='sha256-[a-zA-Z0-9+/]*=*'|integrity='sha256-$NEW_HASH'|g" Presentation/release/wwwroot/index.html

    - name: Copy index.html to 404.html
      run: cp Presentation/release/wwwroot/index.html Presentation/release/wwwroot/404.html  
    
    - name: Add .nojekyll file
      run: touch Presentation/release/wwwroot/.nojekyll 
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        BRANCH: Published
        FOLDER: Presentation/release/wwwroot
        CREATE_BRANCH: true